#! /bin/sh


### AUTOSTART ###
sxhkd &
nitrogen --restore & 
./.config/polybar/launch.sh &

### MONITORS ###
bspc monitor DP-0 -d I II III IV V VI VII VIII IX X
bspc monitor HDMI-0 -d I II III IV V VI VII VIII IX X

### CONFIGURATION ###
bspc config border_width 2
bspc config window_gap 15

bspc config normal_border_color "#1b5b34"
bspc config active_border_color "#28824a"
bspc config focused_border_color "#38b769"

