#! /bin/sh


### AUTOSTART ###
sxhkd &
nitrogen --restore & 
polybar example &

### MONITORS ###
bspc monitor -d I II III IV V VI VII VIII IX X


### CONFIGURATION ###
bspc config border_width 2
bspc config window_gap 15

bspc config normal_border_color "#093049"
bspc config active_border_color "#1076ba"
bspc config focused_border_color "#1076ba"

